#
# Author tinyflag
# Date 2026-02-13
# Name 99-audio-app-routing
# Description apply automatic routing for registered app to sbx_input
#



monitor.rules = [
    {
        matches = [
            {
                application.name = "Chromium"
            },
            {
                application.name = "Firefox"
            },
            {
                application.name = "Brave"
            },
            {
                application.name = "~Chromium.*"
            },           
            {
                application.name = "~Firefox.*"
            },
            {
                application.process.binary = "firefox"
            },
            {
                application.process.binary = "chromium"
            },
            {
                application.process.binary = "chrome"
            },
            {
                application.process.binary = "floorp"
            }
        ]
        actions = {
            update-props = {
                target.object = "sbx_input"
                node.autoconnect = true
            }
        }
    }
]
