#
# Author tinyflag
# Date 2026-02-13
# Name 99-audio-app-routing
# Description apply automatic routing for registered app to sbx_input
#



monitor.rules = [
    {
        matches = [
            {
                # Exact match from your pw-dump
                application.name = "Firefox"
            }
            {
                # Match Firefox
                application.process.binary = "firefox"
            }
            {
                # Match Chromium/Chrome/Brave
                application.process.binary = "chromium"
            }
            {
                # Broad match for Chrome-based browsers
                application.name = "~Chromium.*"
            }
        ]
        actions = {
            update-props = {
                target.object = "sbx_input"
                node.autoconnect = true
            }
        }
    }
]
